### ISSUE TITLE
UI Mockup

### ISSUE THREAD

**Issue by algokun** [AbstractXan/LINK_PUMP#4]
Design a mock-up for the site keeping the MVP in mind.

- Keep it minimal
- No big modals and headings

**Comment by AbstractXan** [comment]
Where to go from here -> Implementing the approved mock-up to #2

**Comment by algokun** [comment]
I have designed the complete prototype of the site in figma and you can find the mockup [here](https://www.figma.com/file/gzUk5IHyuFIYggY5D2aQnj/Link-Pump?node-id=0%3A1)

**Comment by AbstractXan** [comment]
Can you please attach the images in here?

**Comment by algokun** [comment]
> Can you please attach the images in here?

<img width="1440" alt="EXP3" src="https://user-images.githubusercontent.com/21126965/94948234-a1ef0d00-04fc-11eb-9856-e4b174c9cd5f.png">
